In [1]:
# IMDB DATASET
# Movie review dataset

# Implement in Google Colab

In [2]:
# Dataset -> Feature Engg -> Simple RNN -> Streamlit web app -> Deployment

# Simple RNN: Embedding layer and Simple RNN architecture
# Embedding layer (uses word embeddings) for converting words to vectors 
# word2vec is a kind of word embedding techniques

Word embeddings

In [3]:
# word embeddings -> Feature representation

In [4]:
# OHE
# One hot representation
# for ex.: A vocabolary has 10k words, then word "Man" will be converted to vector of (10000,1)
# And every value is zero, only value with "Man" will have a value of 1
# Sparse matrix --> Overfitting

Word embeddings

In [5]:
# Word embeddings
# vocab size in corpus = 10000
# feature dim in word2vec = 300

In [6]:
from tensorflow import keras

In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [9]:
# define vocab size
voc_size=10000

# One hot representaiton for every word
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[522, 1597, 5453, 1077],
 [522, 1597, 5453, 5274],
 [522, 8560, 5453, 4088],
 [831, 822, 378, 9451, 6599],
 [831, 822, 378, 9451, 3575],
 [7998, 522, 2098, 5453, 451],
 [937, 2521, 272, 9451]]

In [11]:
# word embedding representation
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [12]:
# For RNN, we need to make all sentences of equal sizes
# Otherwise we won't be able to train these is RNN
# bcz all the words will be going in fixed no. of time stamps based on the sentence size
# thats why we imported pad_sequences

In [13]:
sent_length = 8 # max length + some buffer
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  522 1597 5453 1077]
 [   0    0    0    0  522 1597 5453 5274]
 [   0    0    0    0  522 8560 5453 4088]
 [   0    0    0  831  822  378 9451 6599]
 [   0    0    0  831  822  378 9451 3575]
 [   0    0    0 7998  522 2098 5453  451]
 [   0    0    0    0  937 2521  272 9451]]


In [14]:
# feature representation
dim=10

In [15]:
# create model (create embedding layer)
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_length=sent_length))
model.compile('adam', 'mse')

d:\Python\GenAI\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [26]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step


array([[[-4.90057357e-02, -4.63413373e-02, -4.11916003e-02,
          2.12304294e-05,  3.87272574e-02, -4.88477610e-02,
         -3.97264138e-02,  1.42695419e-02,  1.25419609e-02,
         -3.01628001e-02],
        [-4.90057357e-02, -4.63413373e-02, -4.11916003e-02,
          2.12304294e-05,  3.87272574e-02, -4.88477610e-02,
         -3.97264138e-02,  1.42695419e-02,  1.25419609e-02,
         -3.01628001e-02],
        [-4.90057357e-02, -4.63413373e-02, -4.11916003e-02,
          2.12304294e-05,  3.87272574e-02, -4.88477610e-02,
         -3.97264138e-02,  1.42695419e-02,  1.25419609e-02,
         -3.01628001e-02],
        [-4.90057357e-02, -4.63413373e-02, -4.11916003e-02,
          2.12304294e-05,  3.87272574e-02, -4.88477610e-02,
         -3.97264138e-02,  1.42695419e-02,  1.25419609e-02,
         -3.01628001e-02],
        [ 1.94309689e-02,  7.58297369e-03, -3.15109119e-02,
         -3.18566784e-02, -9.42207873e-04,  6.81307167e-03,
         -3.31900269e-03,  5.39936870e-03,  2.960306

In [18]:
len(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


7

In [21]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


array([[-4.9005736e-02, -4.6341337e-02, -4.1191600e-02,  2.1230429e-05,
         3.8727257e-02, -4.8847761e-02, -3.9726414e-02,  1.4269542e-02,
         1.2541961e-02, -3.0162800e-02],
       [-4.9005736e-02, -4.6341337e-02, -4.1191600e-02,  2.1230429e-05,
         3.8727257e-02, -4.8847761e-02, -3.9726414e-02,  1.4269542e-02,
         1.2541961e-02, -3.0162800e-02],
       [-4.9005736e-02, -4.6341337e-02, -4.1191600e-02,  2.1230429e-05,
         3.8727257e-02, -4.8847761e-02, -3.9726414e-02,  1.4269542e-02,
         1.2541961e-02, -3.0162800e-02],
       [-4.9005736e-02, -4.6341337e-02, -4.1191600e-02,  2.1230429e-05,
         3.8727257e-02, -4.8847761e-02, -3.9726414e-02,  1.4269542e-02,
         1.2541961e-02, -3.0162800e-02],
       [ 1.9430969e-02,  7.5829737e-03, -3.1510912e-02, -3.1856678e-02,
        -9.4220787e-04,  6.8130717e-03, -3.3190027e-03,  5.3993687e-03,
         2.9603068e-02, -1.5741121e-02],
       [ 2.1602515e-02, -2.0642877e-02, -2.9174292e-02,  2.7431022e-02,
   

In [20]:
len(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step


8

In [22]:
len(model.predict(embedded_docs)[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step


10

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0,  522, 1597, 5453, 1077])

In [25]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step


array([[-4.9005736e-02, -4.6341337e-02, -4.1191600e-02,  2.1230429e-05,
         3.8727257e-02, -4.8847761e-02, -3.9726414e-02,  1.4269542e-02,
         1.2541961e-02, -3.0162800e-02],
       [-4.9005736e-02, -4.6341337e-02, -4.1191600e-02,  2.1230429e-05,
         3.8727257e-02, -4.8847761e-02, -3.9726414e-02,  1.4269542e-02,
         1.2541961e-02, -3.0162800e-02],
       [-4.9005736e-02, -4.6341337e-02, -4.1191600e-02,  2.1230429e-05,
         3.8727257e-02, -4.8847761e-02, -3.9726414e-02,  1.4269542e-02,
         1.2541961e-02, -3.0162800e-02],
       [-4.9005736e-02, -4.6341337e-02, -4.1191600e-02,  2.1230429e-05,
         3.8727257e-02, -4.8847761e-02, -3.9726414e-02,  1.4269542e-02,
         1.2541961e-02, -3.0162800e-02],
       [ 1.9430969e-02,  7.5829737e-03, -3.1510912e-02, -3.1856678e-02,
        -9.4220787e-04,  6.8130717e-03, -3.3190027e-03,  5.3993687e-03,
         2.9603068e-02, -1.5741121e-02],
       [ 2.1602515e-02, -2.0642877e-02, -2.9174292e-02,  2.7431022e-02,
   